### ISSUE TITLE
Recommendations Package Causes Error Due to options.emitMetric being undefined.

### ISSUE THREAD

**Issue by nkbelow** [QubitProducts/qubit-cli#350]
I don't have access to the repo, but was going to submit a PR such as below:
<img width="1126" alt="screen shot 2018-10-03 at 4 03 30 pm" src="https://user-images.githubusercontent.com/22465670/46444229-eab13700-c725-11e8-8aff-e3bf01fa6ea6.png">

Below emitCustomGoal I would like to add emitMetric due to the fact that the new recommendation package uses this and when building using the CLI, you will get an error due to this method being undefined. [usage of emitMetric in the shown and clicked methods](https://github.com/QubitProducts/recommendations/blob/master/index.js)

Any chance this could be added or I could get access to submit a PR? Thanks!

**Comment by samuelfullerthomas** [comment]
thanks for the issue @nkbelow I'm releasing a fix now
