### ISSUE TITLE
ERROR (BUG?): Unable to login with fresh install of node + qubit-cli

### ISSUE THREAD

**Issue by bRRRITSCOLD** [QubitProducts/qubit-cli#465]
Specs
OS: macOS Monterey 12.1
CPU: 2.6 GHz 6-Core Intel Core i7
Memory: 16 GB 2667 MHz DDR4
Graphics: AMD Radeon Pro 5300M 4 GB - Intel UHD Graphics 630 1536 MB
Node Version: v16.13.2
qubit-cli version: 1.77.9 (latest)

Unable to run `qubit login` to login after installing fresh version of Node (v16.13.2) and fresh `npm install -g qubit-cli`. It attempts to go to your private registry before allowing me to login?

<img width="1274" alt="Screen Shot 2022-01-27 at 11 52 25 AM" src="https://user-images.githubusercontent.com/31289446/151409430-b6aa53cd-2652-4332-9caa-1bdef4ebccd4.png">

**Comment by bRRRITSCOLD** [comment]
Also, I have an empty global `.npmrc` and no local `.npmrc`

**Comment by jsonDaCruzo** [comment]
Hi @bRRRITSCOLD, thanks for opening this ticket. We think we’ve found the cause and have made an update. Could you try uninstalling and reinstalling Qubit CLI and confirm whether you are able to login successfully? Here’s the command to do so:
`rm -rf ~/.qubitrc && npm uninstall -g qubit-cli && npm install -g qubit-cli`

**Comment by bRRRITSCOLD** [comment]
@jsonDaCruzo We are cooking with peanut oil now, auto loading the login page on reinstall now - thanks a ton!

<img width="1228" alt="Screen Shot 2022-01-27 at 1 11 34 PM" src="https://user-images.githubusercontent.com/31289446/151418833-70484ae6-5449-406b-9ad3-0fecbf89a677.png">

**Comment by jsonDaCruzo** [comment]
Perfect. Not only am I happy that it's working, but your confirmation message is the best
